#############################################################################
# Makefile for building: huaweicalc
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? ??? 15 12:37:25 2014
# Project:  qtcalc.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile qtcalc.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lcrypto -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = calc.cpp \
		calcdialog.cpp \
		encrypt_1.cpp \
		encrypt_2.cpp \
		encrypt_3.cpp \
		encrypt_4.cpp \
		encrypt_5_v2.cpp \
		encrypt_6.cpp \
		encrypt_7.cpp \
		encrypt_v1.cpp \
		main.cpp moc_calcdialog.cpp \
		qrc_huaweicalc.cpp
OBJECTS       = calc.o \
		calcdialog.o \
		encrypt_1.o \
		encrypt_2.o \
		encrypt_3.o \
		encrypt_4.o \
		encrypt_5_v2.o \
		encrypt_6.o \
		encrypt_7.o \
		encrypt_v1.o \
		main.o \
		moc_calcdialog.o \
		qrc_huaweicalc.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qtcalc.pro
QMAKE_TARGET  = huaweicalc
DESTDIR       = 
TARGET        = huaweicalc

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_calc.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtcalc.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile qtcalc.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qtcalc.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/huaweicalc1.0.0 || $(MKDIR) .tmp/huaweicalc1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/huaweicalc1.0.0/ && $(COPY_FILE) --parents calcdialog.h encrypt.h .tmp/huaweicalc1.0.0/ && $(COPY_FILE) --parents huaweicalc.qrc .tmp/huaweicalc1.0.0/ && $(COPY_FILE) --parents calc.cpp calcdialog.cpp encrypt_1.cpp encrypt_2.cpp encrypt_3.cpp encrypt_4.cpp encrypt_5_v2.cpp encrypt_6.cpp encrypt_7.cpp encrypt_v1.cpp main.cpp .tmp/huaweicalc1.0.0/ && $(COPY_FILE) --parents calc.ui .tmp/huaweicalc1.0.0/ && (cd `dirname .tmp/huaweicalc1.0.0` && $(TAR) huaweicalc1.0.0.tar huaweicalc1.0.0 && $(COMPRESS) huaweicalc1.0.0.tar) && $(MOVE) `dirname .tmp/huaweicalc1.0.0`/huaweicalc1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/huaweicalc1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_calcdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calcdialog.cpp
moc_calcdialog.cpp: ui_calc.h \
		calcdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) calcdialog.h -o moc_calcdialog.cpp

compiler_rcc_make_all: qrc_huaweicalc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_huaweicalc.cpp
qrc_huaweicalc.cpp: huaweicalc.qrc \
		icon.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name huaweicalc huaweicalc.qrc -o qrc_huaweicalc.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_calc.h
compiler_uic_clean:
	-$(DEL_FILE) ui_calc.h
ui_calc.h: calc.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic calc.ui -o ui_calc.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

calc.o: calc.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calc.o calc.cpp

calcdialog.o: calcdialog.cpp calcdialog.h \
		ui_calc.h \
		encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calcdialog.o calcdialog.cpp

encrypt_1.o: encrypt_1.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_1.o encrypt_1.cpp

encrypt_2.o: encrypt_2.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_2.o encrypt_2.cpp

encrypt_3.o: encrypt_3.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_3.o encrypt_3.cpp

encrypt_4.o: encrypt_4.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_4.o encrypt_4.cpp

encrypt_5_v2.o: encrypt_5_v2.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_5_v2.o encrypt_5_v2.cpp

encrypt_6.o: encrypt_6.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_6.o encrypt_6.cpp

encrypt_7.o: encrypt_7.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_7.o encrypt_7.cpp

encrypt_v1.o: encrypt_v1.cpp encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encrypt_v1.o encrypt_v1.cpp

main.o: main.cpp calcdialog.h \
		ui_calc.h \
		encrypt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_calcdialog.o: moc_calcdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calcdialog.o moc_calcdialog.cpp

qrc_huaweicalc.o: qrc_huaweicalc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_huaweicalc.o qrc_huaweicalc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

